In [8]:
import numpy as np
import random

# Environment setup
grid_size = 5
start_position = (0, 0)
goal_position = (4, 4)
penalty_positions = [(1, 2), (2, 3), (3, 1)]

# Parameters
alpha = 0.1       # Learning rate
gamma = 0.9       # Discount factor
epsilon = 0.2     # Exploration rate
num_episodes = 1000

# Initialize Q-table (grid_size x grid_size x 4 for 4 possible actions: up, down, left, right)
Q_table = np.zeros((grid_size, grid_size, 4))

# Actions: up, down, left, right
actions = {0: (-1, 0), 1: (1, 0), 2: (0, -1), 3: (0, 1)}

def is_valid_position(position):
    """ Check if a position is within grid boundaries """
    return 0 <= position[0] < grid_size and 0 <= position[1] < grid_size

def get_next_position(position, action):
    """ Get the next position after taking an action """
    new_position = (position[0] + actions[action][0], position[1] + actions[action][1])
    return new_position if is_valid_position(new_position) else position

def get_reward(position):
    """ Get the reward for a position """
    if position == goal_position:
        return 10  # Reward for reaching the goal
    elif position in penalty_positions:
        return -5  # Penalty for bad cells
    return -1  # Small penalty for each step to encourage efficient pathfinding

# Training with Q-learning
for episode in range(num_episodes):
    position = start_position
    done = False
    
    while not done:
        # Choose action (epsilon-greedy)
        if random.uniform(0, 1) < epsilon:
            action = random.choice(range(4))  # Explore: random action
        else:
            action = np.argmax(Q_table[position[0], position[1]])  # Exploit: best action
        
        # Take action, observe reward and new position
        new_position = get_next_position(position, action)
        reward = get_reward(new_position)
        
        # Update Q-value
        old_value = Q_table[position[0], position[1], action]
        next_max = np.max(Q_table[new_position[0], new_position[1]])
        Q_table[position[0], position[1], action] = old_value + alpha * (reward + gamma * next_max - old_value)
        
        # Move to the new position
        position = new_position
        
        # End episode if goal is reached
        if position == goal_position:
            done = True

print("Training completed!")
print("Learned Q-table values:")
print(Q_table)

# Test the agent by letting it navigate the grid
def test_agent():
    position = start_position
    path = [position]
    while position != goal_position:
        action = np.argmax(Q_table[position[0], position[1]])
        position = get_next_position(position, action)
        path.append(position)
    return path

# Display the path taken by the agent after training
path_taken = test_agent()
print("\nPath taken by the agent to reach the goal:")
print(path_taken)

Training completed!
Learned Q-table values:
[[[-1.40066796 -0.434062   -1.39342076 -0.55464024]
  [-2.4411024   0.6103828  -2.61604356 -2.64824611]
  [-2.19929464 -2.47539381 -2.08284723 -1.92913212]
  [-1.45635387 -1.32693586 -1.37760566 -0.56523978]
  [-0.85640648  2.02583199 -0.94859943 -0.80523444]]

 [[-1.40656629  0.62882    -0.44171601  0.61750601]
  [-1.32393912  1.80979957 -1.51793108 -3.48086447]
  [-1.14867031  3.05316678 -0.59546113 -0.39054555]
  [-1.08037782 -1.98885357 -1.87192333  2.15739881]
  [-0.67212963  5.76862932 -0.74745921 -0.12615481]]

 [[-0.46717129 -0.4565837   0.60679815  1.8098    ]
  [ 0.61677241 -0.90530714  0.60487278  3.122     ]
  [-2.40827629  4.58        1.77209142  0.50187198]
  [-0.358923    6.19791062  1.32218534  1.5572133 ]
  [ 1.15853076  7.99970497 -0.33054849  2.65280046]]

 [[ 0.62553423 -1.75413671 -1.29206839 -1.75843453]
  [-0.26496758  0.35938096 -0.61382894  4.57942953]
  [ 3.09344203  5.59452707 -0.94210066  6.2       ]
  [ 0.4760192 

In [14]:
import pandas as pd
import numpy as np

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
###### helper functions. Use them when needed #######
def get_title_from_index(index):
	return df[df.index == index]["title"].values[0]

def get_index_from_title(title):
	return df[df.title == title]["index"].values[0]

In [17]:
df = pd.read_csv("movie_dataset.csv")
#print df.head()

In [18]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 5AAB-3A19

 Directory of C:\Users\btmsakla

11/05/2024  06:14 AM    <DIR>          .
11/05/2024  06:14 AM    <DIR>          ..
06/19/2024  02:25 PM    <DIR>          .anaconda
07/25/2024  11:11 AM    <DIR>          .android
10/28/2019  08:24 AM    <DIR>          .AndroidStudio3.5
06/29/2020  09:28 AM    <DIR>          .AndroidStudio4.0
09/07/2020  01:04 AM                90 .angular-config.json
09/20/2023  06:01 PM    <DIR>          .arduinoIDE
10/08/2024  02:49 PM    <DIR>          .cache
06/19/2024  02:24 PM    <DIR>          .conda
06/20/2024  01:08 PM                43 .condarc
06/18/2024  08:57 AM    <DIR>          .config
06/19/2024  02:24 PM    <DIR>          .continuum
08/26/2020  09:08 AM    <DIR>          .cordova
11/28/2019  02:14 PM             1,038 .csslintrc
05/12/2020  01:35 PM    <DIR>          .dbus-keyrings
03/04/2021  01:42 PM    <DIR>          .designer
01/18/2021  09:43 AM    <DIR>          .dotnet
08/05/2020 

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [20]:

features = ['keywords','cast','genres','director']

In [21]:
def combine_features(row):
  return row['keywords'] + " "+ row['cast'] + " "+ row["genres"] +" "+ row["director"]

for feature in features:
  df[feature] = df[feature].fillna('') 
  
#except:
 # print "Error:", row
  
df["combined_features"]=df.apply(combine_features,axis=1)

print ("Combined_Features:", df["combined_features"].head())

Combined_Features: 0    culture clash future space war space colony so...
1    ocean drug abuse exotic island east india trad...
2    spy based on novel secret agent sequel mi6 Dan...
3    dc comics crime fighter terrorist secret ident...
4    based on novel mars medallion space travel pri...
Name: combined_features, dtype: object


In [22]:
cv = CountVectorizer()
count_matrix= cv.fit_transform(df["combined_features"])


In [23]:
cosine_sim = cosine_similarity(count_matrix)
movie_user_likes = "Avatar"

In [24]:
movie_index = get_index_from_title(movie_user_likes)
similar_matrix = list(enumerate(cosine_sim[movie_index]))


In [25]:
sorted_similar_movies= sorted(similar_matrix, key=lambda x:x[1], reverse=True)

In [26]:
i=0
for movie in sorted_similar_movies:
 print(get_title_from_index(movie[0]))
 i=i+1
 if i>20:
   break

Avatar
Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Star Trek Into Darkness
Star Trek Beyond
Alien
Lockout
Jason X
The Helix... Loaded
Moonraker
Planet of the Apes
Galaxy Quest
Gravity
Alien³
Jupiter Ascending
The Wolverine
Silent Running
Zathura: A Space Adventure
Trekkies
Cargo
